/**
 * The prose of the generated license documents.
 *
 * Kept apart from the generator so prose claims and computed inventory can be reviewed
 * independently. Identity comes from package.json so the documents describe this project rather
 * than a hardcoded name.
 */

export const NOTICES_INTRO = `
This is the attribution appendix to [\`THIRD_PARTY_LICENSES.md\`](./THIRD_PARTY_LICENSES.md).

The summary document says which licenses are involved. This one reproduces, for every package in
the **runtime closure** (the declared production dependencies and everything they pull in
transitively, as resolved by \`bun.lock\`), the license text and any \`NOTICE\` file the package
itself ships. Optional packages the lockfile resolves for other platforms are included, so this
appendix can be larger than what any one machine installs, never smaller. That is what MIT, BSD,
ISC and Apache-2.0 each require a redistributor to pass on: not only the license identifier, but
the package's own copyright line and terms when the package supplies them.

Generated by \`bun run licenses:generate\`; do not edit by hand.
`;

export const intro = (APP: string, LICENSE: string) => `
${APP} is licensed under the [${LICENSE} License](./LICENSE). This document records the license
inventory of the npm dependencies this repository declares and of the closure \`bun.lock\` resolves
for them. Package-specific terms are reproduced in
[\`THIRD_PARTY_NOTICES.md\`](./THIRD_PARTY_NOTICES.md).

Read the scope section below before treating this as a notice for anything you received: the
published ${APP} package contains no third-party code at all, so this inventory describes what an
install pulls in alongside it, not what the tarball redistributes.
`;

export const DEPENDENCIES_HEADING = 'Runtime dependencies';

export const scopeSections = (BUN_VERSION: string, APP: string, LICENSE: string) => [
	{
		body: `
- **The published package redistributes no third-party code.** \`bun run build:bundle\` passes
  \`--packages=external\`, so \`dist/cli.js\` and \`dist/index.js\` contain first-party source only
  and \`import\` their dependencies at runtime. The tarball ships those two bundles, the type
  declarations, \`README.md\` and \`LICENSE\`. Neither this file nor the notices appendix is
  included, deliberately: a consumer's own resolver decides which versions of these packages it
  installs, so a copy of this repository's lockfile inventory travelling inside the tarball would
  describe versions the consumer may not have.
- **The closure is resolved from the lockfile, not from \`node_modules\`.** It covers the declared
  production dependencies transitively and includes optional packages resolved for platforms other
  than the one generating this file, so it can over-include rather than under-report.
- **Development and build tooling is not inventoried.** It is a devDependency: it is never
  installed by a consumer of the published package and is not part of any artifact.
`,
		heading: 'Scope',
	},
	{
		body: `
\`bun run compile\` produces a single-file executable in \`dist/\`. That artifact is different in
kind from the published npm package: it embeds the JavaScript of the whole runtime closure above
*and* the Bun runtime, which statically links libraries under the LGPL — JavaScriptCore/WebKit
(LGPL-2) and TinyCC (LGPL-2.1) among them.

${APP} does not publish that executable; \`compile\` exists for local use. Anyone who does
distribute it takes on the obligations that come with it: passing on the license texts and
copyright lines in [\`THIRD_PARTY_NOTICES.md\`](./THIRD_PARTY_NOTICES.md), reproducing Bun's own
license, and satisfying the LGPL's source and relink requirements for the statically linked
components. Bun is MIT and published at <https://github.com/oven-sh/bun> (this repository pins
\`bun@${BUN_VERSION}\`, tagged \`bun-v${BUN_VERSION}\`); the patched WebKit/JavaScriptCore it links
is at <https://github.com/oven-sh/webkit>, and TinyCC is at <https://github.com/tinycc/tinycc>.
${APP}'s own source is ${LICENSE}, so nothing here restricts that. A distributor must preserve the
exact corresponding source rather than rely on those upstream locations remaining unchanged.
`,
		heading: 'Not covered: the compiled single-file executable',
	},
];

export interface GeneratedDocuments {
	notices: string;
	summary: string;
}
