/**
 * Synchronized verbatim from Spernakit by scripts/sync-license-core.ts.
 *
 * Do not edit this file here. Changes must originate in Spernakit and be synced outward, or the
 * next sync reverts them without saying so. Exports with no caller in this repository are expected
 * and must not be removed: the licence core is shared, and other adopters consume them. A dead-code
 * report naming an export in this file is not evidence that the export is unused.
 */
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { byCodepoint } from './order.ts';

export type RootDependencyField = 'dependencies' | 'devDependencies' | 'optionalDependencies';

export interface LockedPackage {
	name: string;
	/**
	 * The lockfile entry restricts this package to particular platforms (`os`, `cpu`, or `libc`).
	 *
	 * The lockfile lists every platform's variant of a native package, but an install materializes
	 * only the ones this machine matches. A consumer that reads each resolved package off disk
	 * therefore has to distinguish "not installed because this platform does not use it" from
	 * "not installed because the tree is stale", and only the lockfile knows which. Optional
	 * rather than required so adopters on an older copy of this module keep compiling.
	 */
	platformGated?: boolean;
	version: string;
}

interface LockEntry {
	cpu?: string | string[];
	dependencies?: Record<string, string>;
	libc?: string | string[];
	optionalDependencies?: Record<string, string>;
	optionalPeers?: string[];
	os?: string | string[];
	peerDependencies?: Record<string, string>;
}

interface QueueEntry {
	fromChain: string[];
	fromName: null | string;
	/** Whether every edge walked to reach this package came from a platform-gated parent. */
	gated: boolean;
	name: string;
	optional: boolean;
}

function parseLockfile(text: string): {
	packages: Record<string, unknown>;
	workspaces: Record<string, unknown>;
} {
	const parsed = JSON.parse(text.replace(/,(\s*[}\]])/g, '$1')) as Record<string, unknown>;
	return {
		packages: (parsed.packages ?? {}) as Record<string, unknown>,
		workspaces: (parsed.workspaces ?? {}) as Record<string, unknown>,
	};
}

function packageEntry(value: unknown): { meta: LockEntry; spec: string } | null {
	if (!Array.isArray(value) || typeof value[0] !== 'string') return null;
	// Bun places the dependency-metadata object at different offsets depending on how a package
	// was resolved (registry vs git/github/tarball/folder). Locate it by shape rather than by a
	// fixed index, so an entry whose meta is not element [2] still has its edges walked.
	const meta = value.find(
		(element) => typeof element === 'object' && element !== null && !Array.isArray(element),
	);
	return { meta: (meta as LockEntry | undefined) ?? {}, spec: value[0] };
}

function splitSpec(spec: string): LockedPackage | null {
	const separator = spec.lastIndexOf('@');
	if (separator <= 0) return null;
	return { name: spec.slice(0, separator), version: spec.slice(separator + 1) };
}

function resolveKey(
	packages: Record<string, unknown>,
	fromChain: string[],
	name: string,
): { chain: string[]; key: string } | null {
	for (let depth = fromChain.length; depth >= 0; depth -= 1) {
		const chain = [...fromChain.slice(0, depth), name];
		const key = chain.join('/');
		if (key in packages) return { chain, key };
	}
	return null;
}

function installedDependencies(
	meta: LockEntry,
	includePeerDependencies: boolean,
): { name: string; optional: boolean }[] {
	const dependencies = Object.keys(meta.dependencies ?? {}).map((name) => ({
		name,
		optional: false,
	}));
	dependencies.push(
		...Object.keys(meta.optionalDependencies ?? {}).map((name) => ({ name, optional: true })),
	);

	if (includePeerDependencies) {
		const optionalPeers = new Set(meta.optionalPeers ?? []);
		dependencies.push(
			...Object.keys(meta.peerDependencies ?? {})
				.filter((name) => !optionalPeers.has(name))
				.map((name) => ({ name, optional: false })),
		);
	}
	return dependencies;
}

/**
 * Whether the entry names any platform constraint at all, rather than whether it matches this
 * host. Bun records `os` and `cpu` but not `libc`, so a musl build and a glibc build of the same
 * package are indistinguishable here; evaluating the constraint would call one of them installable
 * on a Linux host that will never install it. Presence is the question that can be answered.
 *
 * Gating is inherited across edges, because reachability is what decides whether an install
 * materializes a package. `@img/sharp-wasm32` declares no constraint of its own and is reached
 * only through `@img/sharp-freebsd-wasm32` (`os: freebsd`) and `@img/sharp-webcontainers-wasm32`
 * (`cpu: none`), so no ordinary install ever writes it to disk, and neither does its own
 * dependency `@emnapi/runtime`. Reading this entry alone called both of them missing installs.
 * A package reachable by any unrestricted path is not gated, which is why the traversal lets an
 * unrestricted arrival overwrite a gated one rather than stopping at the first visit.
 */
function isPlatformGated(meta: LockEntry): boolean {
	return meta.os !== undefined || meta.cpu !== undefined || meta.libc !== undefined;
}

export interface LockfileClosureOptions {
	includePeerDependencies?: boolean;
	internal: ReadonlySet<string>;
	rootFields: readonly RootDependencyField[];
	workspaces: readonly string[];
}

export async function collectLockfileClosure(
	root: string,
	options: LockfileClosureOptions,
): Promise<{ packages: LockedPackage[]; unresolved: string[] }> {
	const lock = parseLockfile(await readFile(join(root, 'bun.lock'), 'utf8'));
	const queue: QueueEntry[] = [];

	for (const workspace of options.workspaces) {
		const value = lock.workspaces[workspace];
		if (typeof value !== 'object' || value === null) continue;
		const manifest = value as Record<string, unknown>;
		for (const field of options.rootFields) {
			const declared = manifest[field];
			if (typeof declared !== 'object' || declared === null) continue;
			for (const name of Object.keys(declared as Record<string, unknown>)) {
				if (!options.internal.has(name)) {
					queue.push({
						fromChain: [],
						fromName: null,
						gated: false,
						name,
						optional: false,
					});
				}
			}
		}
	}

	const resolvedPackages = new Map<string, LockedPackage>();
	const unresolved = new Set<string>();
	// Records the gating each key was last recorded under, not merely that it was seen. A key first
	// reached through a platform-gated parent is revisited if an unrestricted path to it turns up
	// later, so the answer does not depend on which edge the queue happened to walk first. Only
	// that downgrade re-enqueues, so every key is processed at most twice and the walk terminates.
	const visited = new Map<string, boolean>();

	while (queue.length > 0) {
		const item = queue.shift();
		if (item === undefined || options.internal.has(item.name)) continue;
		const resolved = resolveKey(lock.packages, item.fromChain, item.name);
		if (resolved === null) {
			if (!item.optional) {
				unresolved.add(
					item.fromName ? `${item.name} (required by ${item.fromName})` : item.name,
				);
			}
			continue;
		}
		const entry = packageEntry(lock.packages[resolved.key]);
		const gated = item.gated || (entry !== null && isPlatformGated(entry.meta));
		// Revisit only to relax a gating already recorded; an equal or stricter arrival adds nothing.
		if (visited.has(resolved.key) && !(visited.get(resolved.key) === true && !gated)) continue;
		visited.set(resolved.key, gated);

		const locked = entry === null ? null : splitSpec(entry.spec);
		if (entry === null || locked === null) {
			// The key exists in the lockfile but the entry does not parse: surface it as
			// unresolved rather than dropping a package (and its subtree) from the closure.
			if (!item.optional) {
				unresolved.add(
					item.fromName ? `${item.name} (required by ${item.fromName})` : item.name,
				);
			}
			continue;
		}
		if (options.internal.has(locked.name)) continue;
		resolvedPackages.set(`${locked.name}@${locked.version}`, {
			...locked,
			platformGated: gated,
		});

		for (const dependency of installedDependencies(
			entry.meta,
			options.includePeerDependencies ?? false,
		)) {
			queue.push({
				fromChain: resolved.chain,
				fromName: locked.name,
				gated,
				name: dependency.name,
				optional: dependency.optional,
			});
		}
	}

	return {
		packages: [...resolvedPackages.values()].sort(
			(a, b) => byCodepoint(a.name, b.name) || byCodepoint(a.version, b.version),
		),
		unresolved: [...unresolved].sort(byCodepoint),
	};
}
