/**
 * Synchronized verbatim from Spernakit by scripts/sync-license-core.ts.
 *
 * Do not edit this file here. Changes must originate in Spernakit and be synced outward, or the
 * next sync reverts them without saying so. Exports with no caller in this repository are expected
 * and must not be removed: the licence core is shared, and other adopters consume them. A dead-code
 * report naming an export in this file is not evidence that the export is unused.
 */
/** Locale-independent ordering for deterministic generated compliance documents. */
export function byCodepoint(a: string, b: string): number {
	if (a < b) return -1;
	return a > b ? 1 : 0;
}
